(self.AMP=self.AMP||[]).push({n:"amp-lightbox",ev:"0.1",l:true,v:"2105210438003",m:0,f:(function(AMP,_){
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function m(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};
function ca(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ca(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var da={a:!0},q={};try{q.__proto__=da;p=q.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=n;
function t(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(r)r(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ra=b.prototype}var u;function ea(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function fa(a){return a?Array.prototype.slice.call(a):[]}function ha(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};var ia=Object.prototype.hasOwnProperty;function v(a){return a||{}};function w(){this.D=null}f=w.prototype;f.add=function(a){var b=this;this.D||(this.D=[]);this.D.push(a);return function(){b.remove(a)}};f.remove=function(a){if(this.D){var b=this.D;a=b.indexOf(a);-1!=a&&b.splice(a,1)}};f.removeAll=function(){this.D&&(this.D.length=0)};f.fire=function(a){if(this.D)for(var b=m(this.D),c=b.next();!c.done;c=b.next())c=c.value,c(a)};f.getHandlerCount=function(){var a,b;return null!=(b=null==(a=this.D)?void 0:a.length)?b:0};function ja(a){for(var b=null,c="",d=m(arguments),e=d.next();!e.done;e=d.next())if(e=e.value,e instanceof Error&&!b){var g=b=void 0;if(null==(g=Object.getOwnPropertyDescriptor(e,"message"))?0:g.writable)b=e;else{g=e.stack;var h=Error(e.message);for(b in e)h[b]=e[b];h.stack=g;b=h}}else c&&(c+=" "),c+=e;b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function ka(a){var b=ja.apply(null,arguments);setTimeout(function(){var c,d;null==(d=(c=self).__AMP_REPORT_ERROR)||d.call(c,b);throw b;})}
function x(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];try{a.apply(null,c)}catch(e){ka(e)}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}}function na(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ma(c[1],c[1]);c=c[2]?ma(c[2].replace(/\+/g," "),c[2]):"";b[d]=c}return b};var y="";
function oa(a){var b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=na(b.location.originalHash||b.location.hash);y||(y=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012105210438003");var d=na(b.location.originalHash||b.location.hash);d=!(!["1","actions","amp","amp4ads","amp4email"].includes(d.development)&&!b.AMP_DEV_MODE);c=b.__AMP_MODE={localDev:!1,development:d,examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,test:!1,log:c.log,version:"2105210438003",rtvVersion:y}}return c};function pa(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(h){for(var k=[],l=0;l<arguments.length;++l)k[l-0]=arguments[l];e=a.Date.now();g=k;d||(d=a.setTimeout(c,500))}};var z=self.AMP_CONFIG||{},qa=("string"==typeof z.cdnProxyRegex?new RegExp(z.cdnProxyRegex):z.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ra(a){if(self.document&&self.document.head&&(!self.location||!qa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}z.cdnUrl||ra("runtime-host");z.geoApiUrl||ra("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function sa(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function B(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");};function C(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return E(a,b)}function F(a,b){var c=G(a);c=ua(c);return E(c,b)}function va(a){a=G(a);a=ua(a);return wa(a,"action")?E(a,"action"):null}function G(a){return a.nodeType?C((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function ua(a){a=G(a);return a.isSingleDoc()?a.win:a}function E(a,b){wa(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function wa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function xa(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function ya(a){return a.closest?a.closest(".i-amphtml-fie"):xa(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,".i-amphtml-fie"):!1})}function H(a){try{a.focus()}catch(b){}};function I(a){return F(a,"owners")};function J(a,b){var c=this;this.Aa=E(a,"timer");this.Ha=b;this.Ga=0;this.S=-1;this.fa=0;this.la=!1;this.Ca=function(){c.ba()}}J.prototype.isPending=function(){return-1!=this.S};J.prototype.schedule=function(a){var b=a||this.Ga;this.la&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.fa?(this.cancel(),this.fa=c,this.S=this.Aa.delay(this.Ca,b),!0):!1};J.prototype.ba=function(){this.S=-1;this.fa=0;this.la=!0;this.Ha();this.la=!1};
J.prototype.cancel=function(){this.isPending()&&(this.Aa.cancel(this.S),this.S=-1)};var K;function za(a){if(void 0!==K)return K;K=!1;try{var b={get passive(){K=!0;return!1}};a.addEventListener("test-options",null,b);a.removeEventListener("test-options",null,b)}catch(c){}return K};function Aa(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function Ba(a,b,c){this.F=a;this.h=[];this.N=[];this.B=[];this.j=[];this.o=null;this.Oa=b;this.Pa=c;this.ca=!1;this.ba=new J(a.ownerDocument.defaultView,this.va.bind(this));this.xa=new w;this.R=Object.create(null);this.ta=this.Na.bind(this);this.ra=this.La.bind(this);this.sa=this.Ma.bind(this);this.qa=this.Ka.bind(this);var d=za(a.ownerDocument.defaultView);this.F.addEventListener("touchstart",this.ta,d?{passive:!0}:!1);this.F.addEventListener("touchend",this.ra);this.F.addEventListener("touchmove",
this.sa,d?{passive:!0}:!1);this.F.addEventListener("touchcancel",this.qa);this.ha=!1}function Ca(a){var b=void 0===b?!1:b;var c=void 0===c?!1:c;var d=a.__AMP_Gestures;d||(d=new Ba(a,b,c),a.__AMP_Gestures=d);return d}f=Ba.prototype;f.cleanup=function(){this.F.removeEventListener("touchstart",this.ta);this.F.removeEventListener("touchend",this.ra);this.F.removeEventListener("touchmove",this.sa);this.F.removeEventListener("touchcancel",this.qa);delete this.F.__AMP_Gestures;this.ba.cancel()};
f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.R[d];e||(this.h.push(c),e=new w,this.R[d]=e);return e.add(b)};f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.R[b]){a.removeAll();a=ha(this.h,function(c){return c.getType()==b});if(0>a)return!1;this.h.splice(a,1);this.B.splice(a,1);this.j.splice(a,1);this.N.splice(a,1);delete this.R[b];return!0}return!1};f.onPointerDown=function(a){return this.xa.add(a)};
f.Na=function(a){var b=Date.now();this.ca=!1;this.xa.fire(a);for(var c=0;c<this.h.length;c++)if(!this.B[c]&&(this.j[c]&&this.j[c]<b&&L(this,c),this.h[c].onTouchStart(a))){var d=c;this.N[d]=!0;this.j[d]=0}M(this,a)};f.Ma=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)this.N[c]&&(this.j[c]&&this.j[c]<b?L(this,c):this.h[c].onTouchMove(a)||L(this,c));M(this,a)};
f.La=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)if(this.N[c])if(this.j[c]&&this.j[c]<b)L(this,c);else{this.h[c].onTouchEnd(a);var d=!this.j[c],e=this.j[c]<b;this.o!=this.h[c]&&(d||e)&&L(this,c)}M(this,a)};f.Ka=function(a){for(var b=0;b<this.h.length;b++){var c=b;this.B[c]=0;L(this,c)}M(this,a)};
function M(a,b){var c=!!a.o||a.ca;a.ca=!1;if(!c)for(var d=Date.now(),e=0;e<a.h.length;e++)if(a.B[e]||a.j[e]&&a.j[e]>=d){c=!0;break}c?(b.stopPropagation(),a.Oa||b.preventDefault()):a.Pa&&b.stopPropagation();a.ha&&(a.ha=!1,a.va())}
f.va=function(){for(var a=Date.now(),b=-1,c=0;c<this.h.length;c++)if(!this.B[c])this.j[c]&&this.j[c]<a&&L(this,c);else if(-1==b||this.B[c]>this.B[b])b=c;if(-1!=b){var d=0;for(c=0;c<this.h.length;c++)!this.B[c]&&this.N[c]&&(d=Math.max(d,this.j[c]-a));if(2>d){a=b;c=this.h[a];for(var e=0;e<this.h.length;e++)if(e!=a){var g=e;this.B[g]=0;L(this,g)}this.B[a]=0;this.j[a]=0;this.o=c;c.acceptStart()}else this.ba.schedule(d)}};function L(a,b){a.N[b]=!1;a.j[b]=0;a.B[b]||a.h[b].acceptCancel()}
function N(a,b){this.Qa=a;this.aa=b}f=N.prototype;f.getType=function(){return this.Qa};f.signalReady=function(a){var b=this.aa;if(b.o)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.B[d]=c+a,b.j[d]=0);b.ha=!0}};f.signalPending=function(a){var b=this.aa;if(b.o)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.j[d]=c+a)};f.signalEnd=function(){var a=this.aa;a.o==this&&(a.o=null,a.ca=!0)};
f.signalEmit=function(a,b){var c=this.aa.R[this.getType()];c&&c.fire(new Aa(this.getType(),a,Date.now(),b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function Da(a,b,c){1>b&&(b=1);var d=.5+Math.min(b/33.34,.5);return a/b*d+c*(1-d)};function O(a,b,c,d){N.call(this,a,b);this.wa=c;this.Ba=d;this.o=!1;this.pa=this.oa=this.ia=this.$=this.za=this.ka=this.ja=this.K=this.J=this.M=this.L=0}t(O,N);f=O.prototype;f.onTouchStart=function(a){a=a.touches;return this.o&&a&&1<a.length?!0:a&&1==a.length?(this.za=Date.now(),this.L=a[0].clientX,this.M=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1<=b.length){var c=b[0];b=c.clientX;c=c.clientY;this.J=b;this.K=c;if(this.o)P(this,!1,!1,a);else if(a=Math.abs(b-this.L),b=Math.abs(c-this.M),this.wa&&this.Ba)(8<=a||8<=b)&&this.signalReady(-10);else if(this.wa)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.Ba)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};
f.onTouchEnd=function(a){var b=a.touches;b&&0==b.length&&this.o&&(this.o=!1,P(this,!1,!0,a),this.signalEnd())};f.acceptStart=function(){this.o=!0;this.ja=this.L;this.ka=this.M;this.ia=this.za;this.L=this.J;this.M=this.K;P(this,!0,!1,null)};f.acceptCancel=function(){this.o=!1};
function P(a,b,c,d){a.$=Date.now();var e=a.$-a.ia;if(!c&&4<e||c&&16<e){var g=Da(a.J-a.ja,e,a.oa),h=Da(a.K-a.ka,e,a.pa);if(!c||32<e||0!=g||0!=h)a.oa=1E-4<Math.abs(g)?g:0,a.pa=1E-4<Math.abs(h)?h:0;a.ja=a.J;a.ka=a.K;a.ia=a.$}a.signalEmit({first:b,last:c,time:a.$,deltaX:a.J-a.L,deltaY:a.K-a.M,startX:a.L,startY:a.M,lastX:a.J,lastY:a.K,velocityX:a.oa,velocityY:a.pa},d)}function Ea(a){O.call(this,"swipe-xy",a,!0,!0)}t(Ea,O);var Q,Fa="Webkit webkit Moz moz ms O o".split(" "),Ga={getPropertyPriority:function(){return""},getPropertyValue:function(){return""}};function Ha(a,b,c){if(b.startsWith("--"))return b;Q||(Q=Object.create(null));var d=Q[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<Fa.length;g++){var h=Fa[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(Q[b]=d)}return d}
function Ia(a,b){a=a.style;for(var c in b)a.setProperty(Ha(a,c),String(b[c]),"important")}function R(a,b,c){(b=Ha(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function S(a,b){for(var c in b)R(a,c,b[c])}function T(a){"display"in a&&B().error("STYLE","`display` style detected in styles. You must use toggle instead.");return a}function Ja(a){var b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")}
function Ka(a){for(var b=["transition"],c=0;c<b.length;c++)R(a,b[c],null)};var U;v({c:!0,v:!0,a:!0,ad:!0});function La(a){return a.classList.contains("i-amphtml-fie")||!!ya(a)};function Ma(a){return a.unmount()}function Na(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)V(a[b],!1,!0,Ma);else V(a,!1,!0,Ma)}function V(a,b,c,d){if(b&&a.classList.contains("i-amphtml-element")&&(x(d,a),!c)){var e=a.getPlaceholder();e&&V(e,!0,!1,d);return}var g=a.getElementsByClassName("i-amphtml-element");a=null;for(b=0;b<g.length;b++){var h=g[b];if(c)x(d,h);else{a=a||[];for(var k=!1,l=0;l<a.length;l++)if(a[l].contains(h)){k=!0;break}k||(a.push(h),x(d,h))}}};var Oa=['<i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad"><div>Ad</div><i-amphtml-ad-close-button class=amp-ad-close-button></i-amphtml-ad-close-button></i-amphtml-ad-close-header>'],X={"fade-in":{openStyle:v({opacity:1}),closedStyle:v({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:v({transform:"translate(0, 0)"}),closedStyle:v({transform:"translate(0, 100%)"}),durationSeconds:.2},"fly-in-top":{openStyle:v({transform:"translate(0, 0)"}),closedStyle:v({transform:"translate(0, -100%)"}),
durationSeconds:.2}};
function Y(a){var b=AMP.BaseElement.call(this,a)||this;b.na=null;b.C=null;b.P=b.win.document;b.T=null;b.ea=-1;b.U=!1;b.X=null;b.W=null;b.Z=null;b.Y=null;b.ga=null;b.I=!1;b.G=0;b.da=0;b.ma=null;b.V=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.A=null;b.H=null;b.O=null;var c=C(b.win,"platform");b.Ia=c.isIos();b.ua=pa(b.win,function(){var d=sa().assertElement(b.C,"E#19457 this.container_"),e=I(b.element);e.scheduleLayout(b.element,d);e.scheduleResume(b.element,d)});return b}t(Y,AMP.BaseElement);
f=Y.prototype;f.buildCallback=function(){var a=this;this.user().assert(ia.call(X,this.V),"Invalid `animate-in` value %s",this.V);this.element.classList.add("i-amphtml-overlay");this.T=va(this.element);Pa(this);this.registerDefaultAction(function(b){return Qa(a,b.trust,b.caller)},"open");this.registerAction("close",function(b){return a.close(b.trust)});this.T.addToAllowlist("AMP-LIGHTBOX",["open","close"],["email"])};
function Ra(a){fa(a.element.getElementsByClassName("i-amphtml-element")).forEach(function(b){I(a.element).setOwner(b,a.element)})}
function Sa(a){if(!a.C){var b=a.element;a.I=b.hasAttribute("scrollable");var c=a.getRealChildren();a.C=b.ownerDocument.createElement("div");a.I||a.applyFillContent(a.C);b.appendChild(a.C);c.forEach(function(d){a.C.appendChild(d)});a.I&&(Ra(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){Ra(a);Z(a,a.G)}),b.addEventListener("scroll",a.ya.bind(a)));if(!a.I)Ca(b).onGesture(Ea,function(){});Ta(a)}}
f.layoutCallback=function(){u||(u=Promise.resolve(void 0));var a=u;return a};function Qa(a,b,c){if(!a.U){Sa(a);a.X=a.Fa.bind(a);a.P.documentElement.addEventListener("keydown",a.X);a.Z=a.Ja.bind(a);a.P.documentElement.addEventListener("focusin",a.Z);c&&(a.ga=c);var d=new ea,e=d.promise,g=d.resolve;a.getViewport().enterLightboxMode(a.element,e).then(function(){return Ua(a,g,b)})}}f.mutatedAttributesCallback=function(a){var b=a.open;void 0!==b&&(b?Qa(this,2,document.activeElement):this.close(2))};
function Va(a){var b=a.C.querySelector("[autofocus]");b&&H(b)}
function Ua(a,b,c){function d(){a.ua();b()}var e=a.element,g=X[a.V],h=g.durationSeconds,k=g.openStyle,l=g.closedStyle,D=Object.keys(k).map(function(W){return W+" "+h+"s ease-in"}).join(",");a.da++;a.I&&R(e,"webkitOverflowScrolling","touch");R(e,"transition",D);S(e,T(l));Ja(e);a.mutateElement(function(){e.scrollTop=0});Va(a);a.mutateElement(function(){S(e,T(k))});g=a.C;a.I&&(a.ya(),Z(a,a.G));e.addEventListener("transitionend",d);e.addEventListener("animationend",d);a.setAsContainer();var ta=I(a.element);
ta.scheduleLayout(a.element,g);ta.scheduleResume(a.element,g);Wa(a,"lightboxOpen",c);F(a.getAmpDoc(),"history").push(function(){return a.close(c)}).then(function(W){a.ea=W});Xa(a);Ya(a);Za(a);a.U=!0}function Ta(a){var b=a.element;if(null!=b.getAttribute("close-button")){var c=b.ownerDocument||b;U&&U.ownerDocument===c||(U=c.createElement("div"));c=U;c.innerHTML=Oa[0];var d=c.firstElementChild;c.removeChild(d);a.A=d;b.insertBefore(a.A,a.C)}}
function Xa(a){if(a.A){a.W=a.Ea.bind(a);a.A.addEventListener("keydown",a.W);var b;a.measureMutateElement(function(){b=a.A.getBoundingClientRect().height},function(){a.A.classList.add("amp-ad-close-header");Ia(a.C,{"margin-top":b+"px","min-height":"calc(100vh - "+(b+"px)")})})}}function Za(a){if(a.O||a.A)a.Y=a.Da.bind(a),a.H.addEventListener("click",a.Y)}function $a(a){if(a.O||a.A)a.H.removeEventListener("click",a.Y),a.Y=null,a.A&&(a.A.removeEventListener("keydown",a.W),a.W=null)}f.Da=function(){this.close(3)};
f.Fa=function(a){"Escape"==a.key&&(a.preventDefault(),this.close(3))};f.Ea=function(a){"Enter"==a.key&&(a.preventDefault(),this.close(3))};f.close=function(a){var b=this;this.U&&(this.I&&R(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){return ab(b,a)}))};
function ab(a,b){function c(){e==a.da&&(a.collapse(),a.ua())}var d=a.element,e=++a.da;bb(a)?(Ka(d),c()):(d.addEventListener("transitionend",c),d.addEventListener("animationend",c));S(d,T(X[a.V].closedStyle));-1!=a.ea&&F(a.getAmpDoc(),"history").pop(a.ea);a.P.documentElement.removeEventListener("keydown",a.X);a.X=null;a.P.documentElement.removeEventListener("focusin",a.Z);a.Z=null;$a(a);a.removeAsContainer();Na(a.element);I(a.element).schedulePause(a.element,a.C);a.U=!1;Wa(a,"lightboxClose",b);a.ga&&
H(a.ga)}function bb(a){return"inabox"==oa(a.win).runtime||La(a.element)}f.Ja=function(){this.element.contains(document.activeElement)||this.close(3)};
function Ya(a){if(!a.element.contains(document.activeElement)){a:if(a.H)var b=a.H;else if(a.A)b=a.A;else{b=a.element;for(var c=b.querySelectorAll("[on]"),d=0;d<c.length;d++){var e=c[d];if(a.T.hasResolvableActionForTarget(e,"tap",b,e.parentElement)){b=e;break a}}b=void 0}a.H=b;a.H||(b=a.element.getAttribute("data-close-button-aria-label")||"Close the modal",c=a.P.createElement("button"),c.textContent=b,c.classList.add("i-amphtml-screen-reader"),c.tabIndex=-1,a.O=c,a.element.insertBefore(a.O,a.element.firstChild),
a.H=a.O);H(a.H)}}f.ya=function(){var a=this.element.scrollTop;this.Ia&&(0==a?this.element.scrollTop=1:this.element.scrollHeight==a+this.element.offsetHeight&&(this.element.scrollTop=a-1));this.G=a;null===this.ma&&cb(this,a)};
function cb(a,b){a.ma=E(a.win,"timer").delay(function(){if(30>Math.abs(b-a.G)){B().fine("amp-lightbox","slow scrolling: %s - %s",b,a.G);a.ma=null;var c=a.G;B().fine("amp-lightbox","update_");Z(a,c);a.G=c}else B().fine("amp-lightbox","fast scrolling: %s - %s",b,a.G),cb(a,a.G)},100)}function Z(a,b){var c=[];db(a,b,function(d){c.push(d);I(a.element).scheduleLayout(a.element,d)})}
function db(a,b,c){a.na||(a.na={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.na.height,e=fa(a.element.getElementsByClassName("i-amphtml-element")),g=0;g<e.length;g++){for(var h=e[g],k=0,l=h;l&&a.element.contains(l);l=l.offsetParent)k+=l.offsetTop;var D=2*d;k+h.offsetHeight>=b-D&&k<=b+D&&c(h)}}function Pa(a){var b=a.win;La(a.element)&&eb(b,b.document.body)}
function Wa(a,b,c){var d=a.win;var e="amp-lightbox."+b;var g=v({}),h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?e=new d.CustomEvent(e,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(e,!!h.bubbles,!!h.cancelable,g),e=d);a.T.trigger(a.element,b,e,c)}
function eb(a,b){var c={},d=C(a,"ampdoc").getAmpDoc(b);F(d,"mutator").measureMutateElement(b,function(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||Ga)["background-color"]},function(){c.alreadyTransparent||sa().warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.");Ia(b,{background:"transparent"})})}
(function(a){"inabox"==oa().runtime&&eb(window,document.body);a.registerElement("amp-lightbox",Y,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}i-amphtml-ad-close-header{height:60px!important;display:block!important;visibility:visible!important;opacity:0;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:1000!important;display:-ms-flexbox!important;display:flex!important;-ms-flex-align:center!important;align-items:center!important;-ms-flex-pack:right!important;justify-content:right!important;transition:opacity 0.1s ease-in}[animate-in=fly-in-bottom]>i-amphtml-ad-close-header,[animate-in=fly-in-top]>i-amphtml-ad-close-header{transition-delay:0.2s}.amp-ad-close-header{opacity:1!important;box-sizing:border-box;padding:5px;line-height:40px;background-color:#000;color:#fff;font-family:Helvetica,sans-serif;font-size:12px;cursor:pointer}.amp-ad-close-header>:first-child{margin-left:auto!important;pointer-events:none!important}.amp-ad-close-button{display:block!important;background:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='%23fff'%3E%3Cpath d='M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E\") no-repeat;background-position:50%;width:40px;height:40px;pointer-events:none!important;border-radius:40px;margin-left:5px}.amp-ad-close-header:active>.amp-ad-close-button{background-color:hsla(0,0%,100%,0.3)}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-lightbox-0.1.js.map
