(self.AMP=self.AMP||[]).push({n:"amp-accordion",ev:"0.1",l:true,v:"2105210438003",m:0,f:(function(AMP,_){
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var e=b[c];if(e&&e.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;function da(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function r(a,b,c,e){return function(d){return t(d,a,b,c,e)}}function t(a,b,c,e,d){a:{var f=a-0;if(0>=f)a=0;else if(1<=f)a=1;else{for(var g=0,h=1,k=0,l=0;8>l;l++){k=u(f,b,e);var v=(u(f+1E-6,b,e)-k)/1E-6;if(1E-6>Math.abs(k-a)){a=f;break a}if(1E-6>Math.abs(v))break;else k<a?g=f:h=f,f-=(k-a)/v}for(l=0;1E-6<Math.abs(k-a)&&8>l;l++)k<a?(g=f,f=(f+h)/2):(h=f,f=(f+g)/2),k=u(f,b,e);a=f}}0==a?d=0:1==a?d=1:(b=w(0,c,a),c=w(c,d,a),d=w(d,1,a),b=w(b,c,a),c=w(c,d,a),d=w(b,c,a));return d}
function u(a,b,c){if(0==a)return 0;if(1==a)return 1;var e=w(0,b,a),d=w(b,c,a),f=w(c,1,a);e=w(e,d,a);d=w(d,f,a);return w(e,d,a)}function w(a,b,c){return a+c*(b-a)}var ea={linear:function(a){return a},ease:function(a){return t(a,.25,.1,.25,1)},"ease-in":function(a){return t(a,.42,0,1,1)},"ease-out":function(a){return t(a,0,0,.58,1)},"ease-in-out":function(a){return t(a,.42,0,.58,1)}};
function x(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return r(b[0],b[1],b[2],b[3])}return null}return ea[a]}return a};var y=self.AMP_CONFIG||{},fa=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function z(a){if(self.document&&self.document.head&&(!self.location||!fa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}y.cdnUrl||z("runtime-host");y.geoApiUrl||z("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function C(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}function D(a,b,c){B().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function E(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return F(a,b)}function ha(a){a=G(a);a=G(a);a=a.isSingleDoc()?a.win:a;return H(a,"action")?F(a,"action"):null}function G(a){return a.nodeType?E((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a,b){H(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function H(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var I={bubbles:!0,cancelable:!0};function ia(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null};function ja(){}function J(a){this.A=a;this.D=E(self,"vsync");this.I=null;this.h=[]}function ka(a,b,c){var e=la;return(new J(a)).setCurve(e).add(0,b,1).start(c)}J.prototype.setCurve=function(a){a&&(this.I=x(a));return this};J.prototype.add=function(a,b,c,e){this.h.push({delay:a,func:b,duration:c,curve:x(e)});return this};J.prototype.start=function(a){return new K(this.D,this.A,this.h,this.I,a)};
function K(a,b,c,e,d){this.D=a;this.A=b;this.h=[];for(b=0;b<c.length;b++){var f=c[b];this.h.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||e,started:!1,completed:!1})}this.O=d;this.T=Date.now();this.F=!0;this.L={};c=new da;this.K=c.promise;this.S=c.resolve;this.R=c.reject;this.M=this.D.createAnimTask(this.A,{mutate:this.U.bind(this)});this.D.canAnimate(this.A)?this.M(this.L):(C().warn("Animation","cannot animate"),L(this,!1,0))}
K.prototype.then=function(a,b){return a||b?this.K.then(a,b):this.K};K.prototype.thenAlways=function(a){a=a||ja;return this.then(a,a)};K.prototype.halt=function(a){L(this,!1,a||0)};function L(a,b,c){if(a.F){a.F=!1;if(0!=c){1<a.h.length&&a.h.sort(function(d,f){return d.delay+d.duration-(f.delay+f.duration)});try{if(0<c)for(c=0;c<a.h.length;c++)a.h[c].func(1,!0);else for(var e=a.h.length-1;0<=e;e--)a.h[e].func(0,!1)}catch(d){C().error("Animation","completion failed: "+d,d),b=!1}}b?a.S():a.R()}}
K.prototype.U=function(){if(this.F){for(var a=Date.now(),b=Math.min((a-this.T)/this.O,1),c=0;c<this.h.length;c++){var e=this.h[c];!e.started&&b>=e.delay&&(e.started=!0)}for(c=0;c<this.h.length;c++)if(e=this.h[c],e.started&&!e.completed)a:{var d;if(0<e.duration){var f=d=Math.min((b-e.delay)/e.duration,1);if(e.curve&&1!=f)try{f=e.curve(d)}catch(g){C().error("Animation","step curve failed: "+g,g);L(this,!1,0);break a}}else f=d=1;1==d&&(e.completed=!0);try{e.func(f,e.completed)}catch(g){C().error("Animation",
"step mutate failed: "+g,g),L(this,!1,0)}}1==b?L(this,!0,0):this.D.canAnimate(this.A)?this.M(this.L):(C().warn("Animation","cancel animation"),L(this,!1,0))}};var M,O="Webkit webkit Moz moz ms O o".split(" ");function P(a,b,c){if(b.startsWith("--"))return b;M||(M=Object.create(null));var e=M[b];if(!e||c){e=b;if(void 0===a[b]){var d=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<O.length;f++){var g=O[f]+d;if(void 0!==a[g]){d=g;break a}}d=""}var h=d;void 0!==a[h]&&(e=h)}c||(M[b]=e)}return e}function Q(a,b,c){(b=P(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function R(a,b){for(var c in b)Q(a,c,b[c])};function S(a,b){return function(c,e){for(var d in b){var f=d;"display"===f&&C().error("STYLE","`display` style detected. You must use toggle instead.");Q(a,f,b[d](c,e))}}}function T(a,b){return function(c){return a+(b-a)*c}}function ma(a){return function(b){return a(b)+"px"}};var na=r(.47,0,.745,.715),la=r(.39,.575,.565,1);function U(a){var b=AMP.BaseElement.call(this,a)||this;b.C=[];b.G=null;b.B=null;b.H=!1;b.o=null;b.j=null;b.J=a.id?a.id:Math.floor(100*Math.random());return b}var V=AMP.BaseElement;U.prototype=aa(V.prototype);U.prototype.constructor=U;if(q)q(U,V);else for(var W in V)if("prototype"!=W)if(Object.defineProperties){var oa=Object.getOwnPropertyDescriptor(V,W);oa&&Object.defineProperty(U,W,oa)}else U[W]=V[W];U.W=V.prototype;U.prerenderAllowed=function(){return!0};
U.prototype.isLayoutSupported=function(a){return"container"==a};
U.prototype.buildCallback=function(){var a=this;this.j=ha(this.element);this.H=this.element.hasAttribute("disable-session-states");this.G=pa(this);this.B=qa(this);this.o=this.getRealChildren();this.o.forEach(function(b,c){D("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/main/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var e=b.children;D(2==e.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/main/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var d=e["0"],f=e["1"];f.classList.add("i-amphtml-accordion-content");var g=f.getAttribute("id");g||(g=a.J+"_AMP_content_"+c,f.setAttribute("id",g));var h=d.getAttribute("id");h||(h=a.J+"_AMP_header_"+c,d.setAttribute("id",h));a.registerAction("toggle",function(l){return X(a,l)});a.registerAction("expand",function(l){return X(a,l)});a.registerAction("collapse",function(l){return X(a,l)});a.j.addToAllowlist("amp-accordion",["toggle","expand","collapse"],["email"]);(new a.win.MutationObserver(function(l){ra(a,
l)})).observe(b,{attributes:!0,attributeFilter:["data-expand"]});a.B[g]?b.setAttribute("expanded",""):!1===a.B[g]&&b.removeAttribute("expanded");a.mutateElement(function(){});D(!b.hasAttribute("[expanded]")&&!b.hasAttribute("data-amp-bind-expanded"),'The "expanded" attribute cannot be used with amp-bind in version 0.1 of amp-accordion. Please bind to [data-expand] instead. Found in: %s',a.element);var k=b.hasAttribute("expanded");d.classList.add("i-amphtml-accordion-header");d.hasAttribute("role")||
d.setAttribute("role","button");d.setAttribute("aria-controls",g);d.setAttribute("aria-expanded",String(k));d.hasAttribute("tabindex")||d.setAttribute("tabindex",0);a.C.push(d);f.setAttribute("aria-labelledby",h);f.hasAttribute("role")||f.setAttribute("role","region");D(0==a.j.hasAction(d,"tap",b),"amp-accordion headings should not have tap actions registered.");d.addEventListener("click",a.N.bind(a));d.addEventListener("keydown",a.P.bind(a))})};
function X(a,b){var c=b.method,e=b.args,d=b.trust,f=void 0;"expand"===c?f=!0:"collapse"===c&&(f=!1);if(e){var g=e.section,h=a.getAmpDoc().getElementById(g);h=B().assertElement(h);D(h,"No element found with id: %s",g);Y(a,h,d,f)}else for(c=0;c<a.o.length;c++)Y(a,a.o[c],d,f)}function pa(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}
function qa(a){if(a.H)return{};try{var b=a.win.sessionStorage.getItem(a.G);return b?JSON.parse(b):{}}catch(c){return C().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack),{}}}function sa(a){if(!a.H){var b=JSON.stringify(a.B);try{a.win.sessionStorage.setItem(a.G,b)}catch(c){C().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack)}}}
function Z(a,b,c,e){var d=a.win;var f="accordionSection."+b;var g={};var h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?f=new d.CustomEvent(f,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(f,!!h.bubbles,!!h.cancelable,g),f=d);a.j.trigger(c,b,f,e);a=a.element;c=a.ownerDocument.createEvent("Event");c.data={};c.initEvent(b,I.bubbles,I.cancelable);a.dispatchEvent(c)}
function Y(a,b,c,e){var d=b.children,f=d[0];d=d[1].getAttribute("id");var g=b.hasAttribute("expanded"),h=void 0==e?!b.hasAttribute("expanded"):e;h&&b.hasAttribute("expanded")||!h&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?h?(f.setAttribute("aria-expanded","true"),ta(a,b,c),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(k){k!=b&&(ua(a,k,c),k.children[0].setAttribute("aria-expanded","false"))})):(f.setAttribute("aria-expanded","false"),ua(a,b,c)):a.mutateElement(function(){h?
(Z(a,"expand",b,c),b.setAttribute("expanded",""),f.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(k){k!=b&&(k.hasAttribute("expanded")&&(Z(a,"collapse",k,c),k.removeAttribute("expanded")),k.children[0].setAttribute("aria-expanded","false"))})):(Z(a,"collapse",b,c),b.removeAttribute("expanded"),f.setAttribute("aria-expanded","false"))},b),a.B[d]=!g,sa(a))}
function ta(a,b,c){var e,d,f,g,h,k=b.children[1];a.measureMutateElement(function(){e=b.offsetWidth;var l=P(k.style,"width",void 0);h=l?l.startsWith("--")?k.style.getPropertyValue(l):k.style[l]:void 0},function(){var l={position:"fixed",width:e+"px",opacity:"0"},v=k.style,N;for(N in l)v.setProperty(P(v,N),String(l[N]),"important");b.hasAttribute("expanded")||b.setAttribute("expanded","")}).then(function(){return a.measureMutateElement(function(){d=b.offsetHeight;f=k.offsetHeight;var l=a.getViewport().getHeight();
g=va(Math.abs(f),l)},function(){R(b,{overflow:"hidden",height:d+"px"});R(k,{position:"",opacity:"",width:h})})}).then(function(){var l=new J(a.element);l.setCurve(na);l.add(0,S(b,{height:ma(T(d,d+f))}),1);l.add(0,S(k,{opacity:T(0,1)}),1);return l.start(g).thenAlways(function(){a.mutateElement(function(){Z(a,"expand",b,c);R(b,{overflow:"",height:""});R(k,{opacity:""})})})})}
function ua(a,b,c){var e,d,f,g=b.firstElementChild;a.measureMutateElement(function(){e=b.offsetHeight;d=g.offsetHeight;var h=a.getViewport().getSize().height;f=va(Math.abs(e),h)},function(){R(b,{overflow:"hidden"})}).then(function(){return ka(b,S(b,{height:ma(T(e,d))}),f).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(Z(a,"collapse",b,c),b.removeAttribute("expanded"));R(b,{height:"",overflow:""})})})})}
function va(a,b){var c=void 0===c?200:c;var e=void 0===e?500:e;return Math.min(Math.max(Math.abs(a)/b*e,c),e)}U.prototype.N=function(a){wa(this,a)&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))};function wa(a,b){var c=b.target;b=b.currentTarget;var e=!!ia(c,function(f){return"A"==f.tagName},b),d=a.j.hasAction(c,"tap",b);return!e&&!d}
U.prototype.P=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.C.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.C.length;0>a&&(a+=this.C.length);try{this.C[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),Y(this,a.currentTarget.parentElement,3))}};
function ra(a,b){b.forEach(function(c){var e=c.target,d=e.hasAttribute("data-expand");e.hasAttribute("expanded")!==d&&Y(a,e,2,d)})}U.prototype.V=function(){return this.j};(function(a){a.registerElement("amp-accordion",U,"amp-accordion>section>:last-child{display:none!important}amp-accordion>section[expanded]>:last-child{display:block!important}.i-amphtml-accordion-content,.i-amphtml-accordion-header{margin:0}.i-amphtml-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion>section:not([expanded]) .i-amphtml-media-component,amp-accordion>section:not([expanded]) .i-amphtml-media-component *{display:none!important;visibility:hidden!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-accordion-0.1.js.map
